<a href="https://colab.research.google.com/github/mohitgupta82345-sys/Data-science-and-visualization/blob/main/Numerical_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3]

In [ ]:
list1

[1, 2, 3]

In [ ]:
array1 = np.array([1,2,3])

In [ ]:
array1

array([1, 2, 3])

In [ ]:
list2=list1*2

In [ ]:
list2

[1, 2, 3, 1, 2, 3]

In [ ]:
array2=array1*2

In [ ]:
print(array2)

[2 4 6]


In [ ]:
## chapter 2

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])

[2 3 4]


In [ ]:
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr2[0:1 , 0:1])

[[1]]


In [ ]:
                                                                  ### num py assiginment.

In [ ]:
## 1.	Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.
arr = np.array([10, 20 , 30 , 40, 50])
print(type(arr))
print(arr.shape)
print(arr.size)
arr.dtype

<class 'numpy.ndarray'>
(5,)
5


dtype('int64')

In [ ]:
## 2.	Create a 3 × 4 array containing numbers from 1 to 12.

arr = np.arange(1, 13).reshape(3, 4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
## 3.	Create an array of zeros, an array of ones, and an identity matrix.
zeros= np.zeros((3,3))
ones = np.ones((3,3))
identity = np.identity(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
##4.	Generate all even numbers between 10 and 50 using np.arange().
arr = np.arange(10, 51, 2)

print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
##5.	Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
                                                                  ## 2. Array Arithmetic

In [ ]:
## 6.	Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.
arr=np.array  ([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("sum:" ,arr+arr2)
print( "diff:" , arr-arr2)
print("multi:" , arr*arr2)
print("divide:" , arr/arr2)

sum: [ 7  9 11 13 15]
diff: [-5 -5 -5 -5 -5]
multi: [ 6 14 24 36 50]
divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
## 7.	Calculate the square and cube of every element in a NumPy array.
arr = np.array([1,2,3])
print(arr**2)
print(arr**3)

[1 4 9]
[ 1  8 27]


In [ ]:
## 8.	Increase every element of an array by 15%.
arr = np.array([1,2,3,4,5])
print(arr*1.15)

[1.15 2.3  3.45 4.6  5.75]


In [ ]:
##9.	Given two arrays, find their element-wise maximum and minimum.
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(np.maximum(arr,arr2))
print(np.minimum(arr,arr2))


[ 6  7  8  9 10]
[1 2 3 4 5]


In [ ]:
                                                              ## 3. Indexing & Slicing

In [ ]:
## 10.	Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.
arr = np.arange(0,21)
print(arr[0:5])
print(arr[16:21])
print(arr[5:16])
print(arr[::2])


[0 1 2 3 4]
[16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
## 11.	Replace the first five elements of an array with 100.
arr = np.array([1,2,3,4,5,6])
arr[0:5]=100
print(arr)

[100 100 100 100 100   6]


In [ ]:
## 12.	Create an array and demonstrate the difference between a slice/view and a copy.


In [ ]:
## 13. Reverse a numpy array using slicing.
arr = np.array([1,2,3,4,5])
arr[ ::-1]


array([5, 4, 3, 2, 1])

In [ ]:
                                                  ## 4. 2-D Array Indexing & Slicing

In [ ]:
##14.	Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.
arr = np.array([[10,20,30] , [40,50,60] , [70,80,90]])
print(arr[1, :])
print(arr[ : , 2])
print(arr[1,1])

[40 50 60]
[30 60 90]
50
