<a href="https://colab.research.google.com/github/mohitgupta82345-sys/Data-science-and-visualization/blob/main/Numerical_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]

In [3]:
list1

[1, 2, 3]

In [4]:
array1 = np.array([1,2,3])

In [5]:
array1

array([1, 2, 3])

In [6]:
list2=list1*2

In [7]:
list2

[1, 2, 3, 1, 2, 3]

In [8]:
array2=array1*2

In [9]:
print(array2)

[2 4 6]


In [10]:
## chapter 2

In [11]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])

[2 3 4]


In [12]:
arr2 = np.array([[1,2,3] , [4,5,6]])
print(arr2[0:1 , 0:1])

[[1]]


In [13]:
                            ## array opratons and broadcasting.
a1 = np.array([100,200,300])
a2 = np.array([1,2,3])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1>=2)
print(a1[a1>=2])


[101 202 303]
[ 99 198 297]
[100 400 900]
[100. 100. 100.]
[ True  True  True]
[100 200 300]


In [14]:
                                              ### num py assiginment.

In [15]:
## 1.	Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.
arr = np.array([10, 20 , 30 , 40, 50])
print(type(arr))
print(arr.shape)
print(arr.size)
arr.dtype

<class 'numpy.ndarray'>
(5,)
5


dtype('int64')

In [16]:
## 2.	Create a 3 × 4 array containing numbers from 1 to 12.

arr = np.arange(1, 13).reshape(3, 4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
## 3.	Create an array of zeros, an array of ones, and an identity matrix.
zeros= np.zeros((3,3))
ones = np.ones((3,3))
identity = np.identity(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
##4.	Generate all even numbers between 10 and 50 using np.arange().
arr = np.arange(10, 51, 2)

print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [19]:
##5.	Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
                                                                  ## 2. Array Arithmetic

In [21]:
## 6.	Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.
arr=np.array  ([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("sum:" ,arr+arr2)
print( "diff:" , arr-arr2)
print("multi:" , arr*arr2)
print("divide:" , arr/arr2)

sum: [ 7  9 11 13 15]
diff: [-5 -5 -5 -5 -5]
multi: [ 6 14 24 36 50]
divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [22]:
## 7.	Calculate the square and cube of every element in a NumPy array.
arr = np.array([1,2,3])
print(arr**2)
print(arr**3)

[1 4 9]
[ 1  8 27]


In [23]:
## 8.	Increase every element of an array by 15%.
arr = np.array([1,2,3,4,5])
print(arr*1.15)

[1.15 2.3  3.45 4.6  5.75]


In [24]:
##9.	Given two arrays, find their element-wise maximum and minimum.
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(np.maximum(arr,arr2))
print(np.minimum(arr,arr2))


[ 6  7  8  9 10]
[1 2 3 4 5]


In [25]:
                                                              ## 3. Indexing & Slicing

In [26]:
## 10.	Create an array from 0 to 20 and extract the first five elements, last five elements, elements from index 5 to 15, and every second element.
arr = np.arange(0,21)
print(arr[0:5])
print(arr[16:21])
print(arr[5:16])
print(arr[::2])


[0 1 2 3 4]
[16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [27]:
## 11.	Replace the first five elements of an array with 100.
arr = np.array([1,2,3,4,5,6])
arr[0:5]=100
print(arr)

[100 100 100 100 100   6]


In [28]:
## 12.	Create an array and demonstrate the difference between a slice/view and a copy.


In [29]:
## 13. Reverse a numpy array using slicing.
arr = np.array([1,2,3,4,5])
arr[ ::-1]


array([5, 4, 3, 2, 1])

In [30]:
                                                  ## 4. 2-D Array Indexing & Slicing

In [31]:
##14.	Create the matrix [[10,20,30],[40,50,60],[70,80,90]]. Extract the second row, third column, and element 50.
arr = np.array([[10,20,30] , [40,50,60] , [70,80,90]])
print(arr[1, :])
print(arr[ : , 2])
print(arr[1,1])
arr2 = np.arange(10 , 101 , 10)
print(arr2)

[40 50 60]
[30 60 90]
50
[ 10  20  30  40  50  60  70  80  90 100]


In [32]:
## 15.	From the matrix above, extract the sub-matrix [[20,30],[50,60]].
matrix = np.array(([20,30] , [50,60]))
print(matrix)

[[20 30]
 [50 60]]


In [35]:
##16.	Create a 5 × 5 matrix containing 1–25 and extract the first row, last column, middle element, and top-left 3 × 3 matrix.
matrix = np.arange(1, 26).reshape(5, 5)
## row
matrix[0, :]


array([ 5, 10, 15, 20, 25])

In [36]:
##coloumn
matrix[:, -1]

array([ 5, 10, 15, 20, 25])

In [39]:
## middele
matrix[2, 2]

np.int64(13)

In [40]:
matrix[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [41]:
## 17.	Create an array containing 1–12 and reshape it into a 3 × 4 matrix.
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
## 18.	Reshape a 1-D array into a 2 × 5 matrix.

arr = np.arange(1, 11)

matrix = arr.reshape(2, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
## 19.	Convert a 3 × 4 matrix into a 4 × 3 matrix using transpose.
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
trans = matrix.T

In [44]:
trans

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [46]:
## 20.	Use transpose() and swapaxes() on a 3-D array.
arr = np.arange(1, 25).reshape(2, 3, 4)
arr.transpose(1, 2, 0)

array([[[ 1, 13],
        [ 2, 14],
        [ 3, 15],
        [ 4, 16]],

       [[ 5, 17],
        [ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23],
        [12, 24]]])

In [47]:
arr.swapaxes(0, 2)

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [50]:
## 21.	Create two 3 × 3 matrices and perform element-wise addition and multiplication.
matrix = np.array(([1,2,3] , [4,5,6] , [7,8,9]))
matrix2 = np.array(([10,11,12] , [13,14,15] , [16,17,18]))
print(matrix+matrix2)

print(matrix*matrix2)

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [51]:
##22.	Calculate the matrix product of two compatible matrices using np.dot().
ans = np.dot(matrix , matrix2)
ans

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [53]:
## 23.	Find the transpose of a matrix and calculate its dot product with the original matrix.
trans = matrix.T
print(trans)
print(np.dot(matrix , trans))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [56]:
## 24.	Calculate the square root of every element in an array using NumPy.

arr = np.array([1, 4, 9, 16, 25])
np.sqrt(arr)

array([1., 2., 3., 4., 5.])

In [64]:
## 25.	Calculate e^x for every element of an array.
arr = np.array([0, 1, 2, 3])
ans = np.exp(arr)
ans

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [72]:
## 26.	Generate a random array and calculate its square root, exponential, and absolute values.
arr = np.random.randn(5)

np.sqrt(arr)



/tmp/ipykernel_1426/813760645.py:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 1.22481268,        nan,        nan])

In [68]:
np.abs(arr)

array([1.36551055, 0.86035053, 2.42131875, 0.16922938, 0.44365897])

In [70]:
np.exp(arr)

array([1.56591446, 0.21018803, 1.40127863, 3.24031884, 0.37671723])

In [74]:
## 27.	Generate two random arrays and find their element-wise maximum.
arr = np.random.randn(5)
arr2 = np.random.randn(5)
np.maximum(arr , arr2)

array([ 1.54148745,  1.34251102,  0.34637579, -1.20782163,  0.41109549])

In [75]:
##28.	Given marks = np.array([35,72,48,90,55,28]), replace marks below 40 with 0 using np.where().
marks = np.array([35,72,48,90,55,28])
np.where(marks<40 , 0 , marks)

array([ 0, 72, 48, 90, 55,  0])

In [82]:
##29.	Given an income array, classify observations as 'High' if income ≥ 50,000 and 'Low' otherwise.

income = np.array([30000, 45000, 50000, 60000, 75000])
con = np.where(income >= 50000, "High", "Low")
con

array(['Low', 'Low', 'High', 'High', 'High'], dtype='<U4')

In [84]:
## 30.	Replace all values greater than 30 in an array with 100 using np.where().

arr = np.array([10, 20, 35, 40, 25, 50])

ans = np.where(arr > 30, 100, arr)
ans

array([ 10,  20, 100, 100,  25, 100])

In [86]:
##31.	Given a 3 × 3 matrix, calculate its total sum, mean, variance, and standard deviation.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

total_sum = np.sum(matrix)
mean = np.mean(matrix)
variance = np.var(matrix)
std_dev = np.std(matrix)

print("Total Sum:", total_sum)
print("Mean:", mean)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Total Sum: 45
Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611


In [90]:
## 32.	Calculate row-wise and column-wise sums using axis.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rowsum = np.sum(matrix, axis=1)
colsum = np.sum(matrix, axis=0)

print("Row-wise Sum:", rowsum)
print("Column-wise Sum:", colsum)

Row-wise Sum: [ 6 15 24]
Column-wise Sum: [12 15 18]


In [91]:
## 33.	Given the marks of 10 students, calculate mean, standard deviation, minimum, and maximum.
marks = np.array([75, 82, 68, 90, 55, 73, 88, 61, 95, 79])
print("Mean:", np.mean(marks))
print("Standard Deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 76.6
Standard Deviation: 12.175385004179539
Minimum: 55
Maximum: 95


In [92]:
##34.	Demonstrate the difference between any() and all() using a Boolean array.
arr = np.array([True, False, True, False])

print("Boolean Array:", arr)

print("Using any():", np.any(arr))
print("Using all():", np.all(arr))

Boolean Array: [ True False  True False]
Using any(): True
Using all(): False


In [94]:
##35.	Generate 10 random numbers and sort them.
arr = np.random.rand(10)
sorted_arr = np.sort(arr)
sorted_arr

array([0.01749576, 0.15348124, 0.17577148, 0.28447529, 0.35974102,
       0.5999774 , 0.78203227, 0.9423555 , 0.96809699, 0.99481488])

In [96]:
## 36.	Given an array containing repeated values, find its unique elements.
arr = np.array([10, 20, 10, 30, 20, 40, 30, 10])
unique_values = np.unique(arr)
unique_values

array([10, 20, 30, 40])

In [97]:
##37.	Given an array of student marks, find the unique marks.
marks = np.array([75, 82, 68, 90, 55, 73, 88, 61, 95, 79])
unique_marks = np.unique(marks)
unique_marks

array([55, 61, 68, 73, 75, 79, 82, 88, 90, 95])

In [101]:
## 38.	Use np.in1d() to check whether selected values occur in an array.
arr = np.array([1, 2, 3, 4, 5])
selected_values = np.array([2,4,6])
result = np.in1d(selected_values, arr)
print(result)

[ True  True False]


/tmp/ipykernel_1426/2145423785.py:4: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  result = np.in1d(selected_values, arr)


In [104]:
## 39.	Student Marks Analysis: Create a NumPy array containing marks of 10 students in 3 subjects. Calculate each student's total and average marks. Identify students whose average is ≥ 50 using np.where().
marks = np.array([[75, 82, 68], [90, 55, 73], [88, 61, 95], [79, 92, 87]])
total_marks = np.sum(marks, axis=1)
average_marks = np.mean(marks, axis=1)
students_above_50 = np.where(average_marks >= 50)[0]
print("Total Marks:", total_marks)
print("Average Marks:", average_marks)
print("Students with Average >= 50:", students_above_50)

Total Marks: [225 218 244 258]
Average Marks: [75.         72.66666667 81.33333333 86.        ]
Students with Average >= 50: [0 1 2 3]


In [105]:
##40.	Matrix Analysis: Create a 4 × 4 matrix containing numbers 1–16. Find its transpose, row-wise sums, column-wise sums, mean, maximum, and minimum. Extract the central 2 × 2 matrix.
matrix = np.arange(1, 17).reshape(4, 4)
print("Original Matrix:")
print(matrix)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [106]:
## 41.	Random Data Analysis: Generate 20 observations using np.random.randn(). Calculate the mean, standard deviation, minimum, maximum, and sorted values. Replace all negative observations with zero using np.where().
observations = np.random.randn(20)
print("Generated Observations:")
print(observations)

Generated Observations:
[ 1.55524584 -0.28048329  0.58082702  1.1097549  -0.01237601 -0.35684639
  0.09241034 -0.64320083  0.6079814   0.3341333   1.18283913 -1.51429306
  0.76201946 -0.7844983   0.72907     0.87172224  0.15357262 -0.72277196
 -1.09312901  0.63228436]


In [109]:
## 42.	Matrix Operations Challenge: Create two 3 × 3 matrices and perform element-wise addition, element-wise multiplication, matrix multiplication, transpose of the first matrix, and maximum/minimum of the resulting matrix.
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3,4,2]])
print(matrix1+matrix2)
print(matrix1*matrix2)
print(np.dot(matrix1 , matrix2))
print(matrix1.T)
print(np.maximum(matrix1 , matrix2))
print(np.minimum(matrix1 , matrix2))

[[10 10 10]
 [10 10 10]
 [10 12 11]]
[[ 9 16 21]
 [24 25 24]
 [21 32 18]]
[[ 30  30  21]
 [ 84  81  60]
 [138 132  99]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[9 8 7]
 [6 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 4]
 [3 4 2]]


In [110]:
##43.	Array Manipulation Challenge: Create an array containing 1–24, reshape it into a 4 × 6 matrix, extract selected rows and columns, transpose it, calculate row/column statistics, and identify unique values.
arr = np.arange(1,25)
matrix = arr.reshape(4,6)

print(matrix[0])
print(matrix[1:3])

print(matrix[:, 0])
print(matrix[:, [1, 3]])

transpose = matrix.T
print(transpose)

print(np.sum(matrix, axis=1))
print(np.mean(matrix, axis=1))
print(np.max(matrix, axis=1))

print(np.sum(matrix, axis=0))
print(np.mean(matrix, axis=0))
print(np.max(matrix, axis=0))

[1 2 3 4 5 6]
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[ 1  7 13 19]
[[ 2  4]
 [ 8 10]
 [14 16]
 [20 22]]
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]
[ 21  57  93 129]
[ 3.5  9.5 15.5 21.5]
[ 6 12 18 24]
[40 44 48 52 56 60]
[10. 11. 12. 13. 14. 15.]
[19 20 21 22 23 24]
